add test
dtm-labs/dtm pull request #103
Opened 2021-12-20 04:23 UTC by li-xiao-shuang

fix #97

2021-12-20 08:08 UTC, yedf2 commented
这里面就一个测试用例，把它放到api_test里面去吧

2021-12-20 08:12 UTC, li-xiao-shuang commented
> 这里面就一个测试用例，把它放到api_test里面去吧

好的

2021-12-20 08:20 UTC, yedf2 requested changes

2021-12-20 08:20 UTC, yedf2 commented on test/api_test.go
> +	rest, err := dtmimp.RestyClient.R().Get("http://localhost:36789/api/metrics")
localhost:36789 可以类似TestAPIQuery那样，用examples.DtmHttpServer

2021-12-20 08:25 UTC, li-xiao-shuang commented on test/api_test.go
> +	rest, err := dtmimp.RestyClient.R().Get("http://localhost:36789/api/metrics")
> localhost:36789 可以类似TestAPIQuery那样，用examples.DtmHttpServer

前缀不一样

2021-12-21 09:20 UTC, lsytj0413 commented
现在 test 目录下的更像是 e2e 测试的样子，要不就放到 test/e2e 目录下吧

2021-12-21 10:52 UTC, yedf2 commented
目前dtm的测试设计，总体上是关注总覆盖率，没有分别去做单元测试的覆盖率和e2e的覆盖率

当前的test目录，其实主要是e2e的测试，如果是单元测试，一般放到源码目录。

我们暂时先不改名了吧，有测试的实质就行

2021-12-27 12:22 UTC, merged