fix golangci lint error
dtm-labs/dtm pull request #157
Opened 2022-01-05 09:48 UTC by Leizhengzi

2022-01-05 15:47 UTC, jxlwqq requested changes

2022-01-05 15:47 UTC, jxlwqq commented on dtmsvr/config/config.go
> +	HTTPPort          int64        `yaml:"HTTPPort" default:"36789"`
这里可能有兼容性问题

2022-01-06 00:42 UTC, yedf2 commented
您好，这个PR太大了，涉及面太广太广，我进行review也会没有把握

能否拆成10个以上的PR，一个改完了再改另一个，逐渐的把golang-ci引入进来，然后把golang-ci放到github的actions里面？

2022-01-06 01:35 UTC, Leizhengzi commented on dtmsvr/config/config.go
> +	HTTPPort          int64        `yaml:"HTTPPort" default:"36789"`
嗯，配置项可能会有影响，我拆分出不同的PR，把影响减少

2022-01-06 01:36 UTC, Leizhengzi commented
> 您好，这个PR太大了，涉及面太广太广，我进行review也会没有把握
> 
> 能否拆成10个以上的PR，一个改完了再改另一个，逐渐的把golang-ci引入进来，然后把golang-ci放到github的actions里面？

嗯，可以，我拆分出不同PR，按影响大小来提交

2022-01-06 01:46 UTC, closed without merging