feat: transOption add requestTimeout option for resets global trans r…
dtm-labs/dtm pull request #222
Opened 2022-02-21 08:05 UTC by Leizhengzi

#204 这是我针对这个issue的一个实现，请审阅下

2022-02-21 10:41 UTC, lizhanfei commented
m一下。这样处理，服务端的

2022-02-21 14:15 UTC, yedf2 requested changes

2022-02-21 14:15 UTC, yedf2 commented on dtmsvr/trans_type_saga.go
> -		case <-time.After(time.Duration(time.Second * 3)):
这个地方可以不需要修改，保留原有的睡眠3s，因为这个地方是输出了一条日志，没有其他作用，不修改更简单

2022-02-21 14:15 UTC, yedf2 commented on test/busi/base_http.go
> +		time.Sleep(time.Second * 4)
这里不要睡眠4s了，否则导致整个单测的时间会加长很多。可以在dtm-examples里面加上示例怎么用

2022-02-22 01:48 UTC, Leizhengzi commented on test/busi/base_http.go
> +		time.Sleep(time.Second * 4)
好的，我回撤下

2022-02-22 01:48 UTC, Leizhengzi commented on dtmsvr/trans_type_saga.go
> -		case <-time.After(time.Duration(time.Second * 3)):
嗯，我回撤下

2022-02-22 01:48 UTC, Leizhengzi commented
> m一下。这样处理，服务端每个请求都会修改RestyClient的超时时间，是否会互相影响。

这个是根据自己的场景加这个选项，不加的话走默认的，不会影响

2022-02-22 02:00 UTC, Leizhengzi commented
> 还有一个是grpc的情况，有空时可以考虑一下方案
好的，我到时候在提交一个pr合并吧

2022-02-22 08:42 UTC, yedf2 approved these changes

2022-02-22 08:42 UTC, merged