Add requestTimeout transOption for grpc request
dtm-labs/dtm pull request #228
Opened 2022-02-24 05:00 UTC by Leizhengzi

#204 grpc的实现，请审阅

2022-02-24 05:48 UTC, yedf2 requested changes

2022-02-24 05:48 UTC, yedf2 commented on dtmgrpc/dtmgpb/dtmgimp.proto
> +  int64 RequestTimeout = 4;
应当把timeout加到最后，否则会有新旧版本兼容问题

2022-02-24 05:48 UTC, yedf2 commented on dtmsvr/trans_status.go
> +		// use ClientInterceptors[1:] for remove default request setting
这种remove的方式可维护性太差，哪天加个中间件，这个代码就出错了，而且是很难诊断的问题
再看看有没有好办法

2022-02-24 05:51 UTC, Leizhengzi commented on dtmgrpc/dtmgpb/dtmgimp.proto
> +  int64 RequestTimeout = 4;
好

2022-02-24 06:58 UTC, Leizhengzi commented on dtmsvr/trans_status.go
> +		// use ClientInterceptors[1:] for remove default request setting
好的，我处理一下

2022-02-24 09:52 UTC, yedf2 requested changes

2022-02-24 09:52 UTC, yedf2 commented on dtmgrpc/dtmgimp/utils.go
> +	if s.RequestTimeout != 0 {
这个逻辑貌似不对，调一次加一个拦截器

2022-02-24 10:05 UTC, Leizhengzi commented on dtmgrpc/dtmgimp/utils.go
> +	if s.RequestTimeout != 0 {
重复设置多次，对于context的withTimeout机制来说，后设置的时间如果大于第一次设置的，倒是不会被覆盖，直接返回第一次的，不过添加多次，不太友好，可以优化一下，我还有一个考虑点就是，这个方法是客户端调用的，如果针对设置了waitResult的，而且也设置requestTimeout的话，我这里是不是要处理2倍的时间，不然客户端也可能会超时退出，不过不应该最终结果

2022-02-25 02:29 UTC, yedf2 commented on test/busi/busi.proto
> +  rpc TransOutWithGlobalRequestTimeout(BusiReq) returns (google.protobuf.Empty) {}
这个地方感觉没必要加，因为设置超时，跟被调用的函数没关系，就调用一个普通的就行。这个应该是最后一个问题了

2022-02-25 03:15 UTC, Leizhengzi commented on test/busi/busi.proto
> +  rpc TransOutWithGlobalRequestTimeout(BusiReq) returns (google.protobuf.Empty) {}
好

2022-02-25 04:13 UTC, yedf2 approved these changes

2022-02-25 04:14 UTC, merged