Feature storage sqlserver
dtm-labs/dtm pull request #467
Opened 2023-10-11 05:50 UTC by wooln

2023-10-29 03:38 UTC, yedf2 requested changes

2023-10-29 03:38 UTC, yedf2 commented on dtmsvr/storage/sql/sql.go
> +	}[conf.Store.Driver]
Since we added sqlserver, then we can eliminate variable `order`, just use one variable `ssql` and add order part in it.

2023-10-29 03:38 UTC, yedf2 commented on client/dtmcli/dtmimp/consts.go
> +	DBTypeSqlServer = "sqlserver"
const DBTypeSqlServer should be DBTypeSQLServer

2023-10-29 03:38 UTC, yedf2 commented on client/dtmcli/dtmimp/db_special.go
> +
If not supporting go client for sqlserver, then these codes should not be added now.

2023-10-29 03:38 UTC, yedf2 commented on client/dtmcli/dtmimp/utils.go
> +func getSqlServerConnectionString(conf *DBConf, host *string) string {
getSqlServerConnectionString should be getSQLServerConnectionString

2023-10-29 03:38 UTC, yedf2 commented on dtmsvr/config/config.go
> +	SqlServer = "sqlserver"
const SqlServer should be SQLServer

2023-10-29 13:19 UTC, wooln commented on client/dtmcli/dtmimp/db_special.go
> +
main_test.go dtmsvr.PopulateDB(false)  invokes GetPlaceHoldSQL(sql).
PopulateDB调用的是不需要通过占位符号传参的固定sql，但之前的路径必然触发sqlserver的GetPlaceHoldSQL。改为有参数时才调用GetPlaceHoldSQL，以避开原始逻辑中需要实现sqlserver版

2023-11-05 07:47 UTC, yedf2 approved these changes

2023-11-05 07:47 UTC, merged